repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: no-commit-to-branch
        name: Don't commit to master
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: local
    hooks:
      - id: black
        name: Black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: system
        require_serial: true
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        args: [
          "src"
        ]
        language: system
        types: [python]
