# conda env create -f environment.yml
#  or
# conda env update -f environment.yml
name: prophet-remade
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Base dependencies
  - python==3.7
  - pandas
  - pip
  - setuptools

  # Notebook stuff
  - ipykernel
  - matplotlib
  # - jupyter
  # - jupyterlab

  # Dev/CI dependencies
  - pre-commit
  - pytest-cov
  - pytest
  - black

  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pip:
    - pyro-ppl

  # Pin pylint/astroid versions to avoid recursion issue mentioned in:
  # https://github.com/PyCQA/pylint/issues/3318.
  - pylint
